builds:
  - binary: xpln
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: xtkt
    homepage: "https://github.com/5amCurfew/xtkt"
    tap:
      owner: 5amCurfew
      name: homebrew-5amCurfew
    commit_author:
      name: 5amCurfew

checksum:
  name_template: 'checksums.txt'